services:
  app:
    platform: linux/amd64
    ports:
      - 3000:8080
    build:
      context: .
      target: development
    volumes:
      - '.:/app'
      - '/app/node_modules'
    container_name: kerrokantasi-ui
