version: '3.8'

services:
  app:
    platform: linux/amd64
    ports:
      - 8086:8086
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    container_name: kerrokantasi-ui
