// flow-typed signature: 7dfbc31b3479e6b8c8d36df1b3b9f497
// flow-typed version: <<STUB>>/alertifyjs_v^1.6.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alertifyjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'alertifyjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'alertifyjs/build/alertify' {
  declare module.exports: any;
}

declare module 'alertifyjs/build/alertify.min' {
  declare module.exports: any;
}

declare module 'alertifyjs/Gruntfile' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/alert' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/alertify' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/confirm' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/actions' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/commands' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/dialog' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/events' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/focus' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/intro' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/move' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/outro' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/resize' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/dialog/transition' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/event' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/intro' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/notifier' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/outro' {
  declare module.exports: any;
}

declare module 'alertifyjs/src/js/prompt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'alertifyjs/build/alertify.js' {
  declare module.exports: $Exports<'alertifyjs/build/alertify'>;
}
declare module 'alertifyjs/build/alertify.min.js' {
  declare module.exports: $Exports<'alertifyjs/build/alertify.min'>;
}
declare module 'alertifyjs/Gruntfile.js' {
  declare module.exports: $Exports<'alertifyjs/Gruntfile'>;
}
declare module 'alertifyjs/src/js/alert.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/alert'>;
}
declare module 'alertifyjs/src/js/alertify.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/alertify'>;
}
declare module 'alertifyjs/src/js/confirm.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/confirm'>;
}
declare module 'alertifyjs/src/js/dialog/actions.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/actions'>;
}
declare module 'alertifyjs/src/js/dialog/commands.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/commands'>;
}
declare module 'alertifyjs/src/js/dialog/dialog.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/dialog'>;
}
declare module 'alertifyjs/src/js/dialog/events.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/events'>;
}
declare module 'alertifyjs/src/js/dialog/focus.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/focus'>;
}
declare module 'alertifyjs/src/js/dialog/intro.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/intro'>;
}
declare module 'alertifyjs/src/js/dialog/move.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/move'>;
}
declare module 'alertifyjs/src/js/dialog/outro.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/outro'>;
}
declare module 'alertifyjs/src/js/dialog/resize.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/resize'>;
}
declare module 'alertifyjs/src/js/dialog/transition.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/dialog/transition'>;
}
declare module 'alertifyjs/src/js/event.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/event'>;
}
declare module 'alertifyjs/src/js/intro.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/intro'>;
}
declare module 'alertifyjs/src/js/notifier.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/notifier'>;
}
declare module 'alertifyjs/src/js/outro.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/outro'>;
}
declare module 'alertifyjs/src/js/prompt.js' {
  declare module.exports: $Exports<'alertifyjs/src/js/prompt'>;
}
