// flow-typed signature: 5c31d4986d0d76b4aab28898dabeaceb
// flow-typed version: <<STUB>>/babel_v^6.1.18/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel/cli.js' {
  declare module.exports: $Exports<'babel/cli'>;
}
declare module 'babel/index' {
  declare module.exports: $Exports<'babel'>;
}
declare module 'babel/index.js' {
  declare module.exports: $Exports<'babel'>;
}
