// flow-typed signature: c3d8b3faf12931857f5a41a753f94656
// flow-typed version: <<STUB>>/hel-bootstrap-3_v^1.0.0-beta.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hel-bootstrap-3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hel-bootstrap-3' {
  declare module.exports: any;
}
