// flow-typed signature: 84ff2a74398850d8488b56faa452078b
// flow-typed version: <<STUB>>/passport-helsinki_vCity-of-Helsinki/passport-helsinki#fec48d78e0258aa1472369014ffc01cd98c7cdc6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-helsinki'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-helsinki' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-helsinki/lib/index' {
  declare module.exports: any;
}

declare module 'passport-helsinki/lib/profile' {
  declare module.exports: any;
}

declare module 'passport-helsinki/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-helsinki/lib/index.js' {
  declare module.exports: $Exports<'passport-helsinki/lib/index'>;
}
declare module 'passport-helsinki/lib/profile.js' {
  declare module.exports: $Exports<'passport-helsinki/lib/profile'>;
}
declare module 'passport-helsinki/lib/strategy.js' {
  declare module.exports: $Exports<'passport-helsinki/lib/strategy'>;
}
