// flow-typed signature: e47280dd8ff1d38521bb31e635b7d9c0
// flow-typed version: <<STUB>>/proj4_v^2.4.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proj4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'proj4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'proj4/dist/proj4-src' {
  declare module.exports: any;
}

declare module 'proj4/dist/proj4' {
  declare module.exports: any;
}

declare module 'proj4/Gruntfile' {
  declare module.exports: any;
}

declare module 'proj4/lib/adjust_axis' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/acosh' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/adjust_lat' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/adjust_lon' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/adjust_zone' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/asinh' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/asinhy' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/asinz' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/atanh' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/clens_cmplx' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/clens' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/cosh' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/e0fn' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/e1fn' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/e2fn' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/e3fn' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/fL' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/gatg' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/gN' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/hypot' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/imlfn' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/inverseNadCvt' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/invlatiso' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/iqsfnz' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/latiso' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/log1py' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/mlfn' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/msfnz' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/nad_cvt' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/nad_intr' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/nadInterBreakout' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/phi2z' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/pj_enfn' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/pj_inv_mlfn' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/pj_mlfn' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/qsfnz' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/sign' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/sinh' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/srat' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/tanh' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/toPoint' {
  declare module.exports: any;
}

declare module 'proj4/lib/common/tsfnz' {
  declare module.exports: any;
}

declare module 'proj4/lib/constants/Datum' {
  declare module.exports: any;
}

declare module 'proj4/lib/constants/Ellipsoid' {
  declare module.exports: any;
}

declare module 'proj4/lib/constants/PrimeMeridian' {
  declare module.exports: any;
}

declare module 'proj4/lib/constants/units' {
  declare module.exports: any;
}

declare module 'proj4/lib/constants/values' {
  declare module.exports: any;
}

declare module 'proj4/lib/core' {
  declare module.exports: any;
}

declare module 'proj4/lib/datum_transform' {
  declare module.exports: any;
}

declare module 'proj4/lib/datum' {
  declare module.exports: any;
}

declare module 'proj4/lib/datumUtils' {
  declare module.exports: any;
}

declare module 'proj4/lib/defs' {
  declare module.exports: any;
}

declare module 'proj4/lib/deriveConstants' {
  declare module.exports: any;
}

declare module 'proj4/lib/extend' {
  declare module.exports: any;
}

declare module 'proj4/lib/global' {
  declare module.exports: any;
}

declare module 'proj4/lib/includedProjections' {
  declare module.exports: any;
}

declare module 'proj4/lib/index' {
  declare module.exports: any;
}

declare module 'proj4/lib/match' {
  declare module.exports: any;
}

declare module 'proj4/lib/parseCode' {
  declare module.exports: any;
}

declare module 'proj4/lib/Point' {
  declare module.exports: any;
}

declare module 'proj4/lib/Proj' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/aea' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/aeqd' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/cass' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/cea' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/eqc' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/eqdc' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/equi' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/etmerc' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/gauss' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/gnom' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/gstmerc' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/krovak' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/laea' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/lcc' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/longlat' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/merc' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/mill' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/moll' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/nzmg' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/omerc' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/ortho' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/poly' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/sinu' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/somerc' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/stere' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/sterea' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/tmerc' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/utm' {
  declare module.exports: any;
}

declare module 'proj4/lib/projections/vandg' {
  declare module.exports: any;
}

declare module 'proj4/lib/projString' {
  declare module.exports: any;
}

declare module 'proj4/lib/transform' {
  declare module.exports: any;
}

declare module 'proj4/lib/version' {
  declare module.exports: any;
}

declare module 'proj4/projs' {
  declare module.exports: any;
}

declare module 'proj4/test/package.json' {
  declare module.exports: any;
}

declare module 'proj4/test/test' {
  declare module.exports: any;
}

declare module 'proj4/test/testData' {
  declare module.exports: any;
}

// Filename aliases
declare module 'proj4/dist/proj4-src.js' {
  declare module.exports: $Exports<'proj4/dist/proj4-src'>;
}
declare module 'proj4/dist/proj4.js' {
  declare module.exports: $Exports<'proj4/dist/proj4'>;
}
declare module 'proj4/Gruntfile.js' {
  declare module.exports: $Exports<'proj4/Gruntfile'>;
}
declare module 'proj4/lib/adjust_axis.js' {
  declare module.exports: $Exports<'proj4/lib/adjust_axis'>;
}
declare module 'proj4/lib/common/acosh.js' {
  declare module.exports: $Exports<'proj4/lib/common/acosh'>;
}
declare module 'proj4/lib/common/adjust_lat.js' {
  declare module.exports: $Exports<'proj4/lib/common/adjust_lat'>;
}
declare module 'proj4/lib/common/adjust_lon.js' {
  declare module.exports: $Exports<'proj4/lib/common/adjust_lon'>;
}
declare module 'proj4/lib/common/adjust_zone.js' {
  declare module.exports: $Exports<'proj4/lib/common/adjust_zone'>;
}
declare module 'proj4/lib/common/asinh.js' {
  declare module.exports: $Exports<'proj4/lib/common/asinh'>;
}
declare module 'proj4/lib/common/asinhy.js' {
  declare module.exports: $Exports<'proj4/lib/common/asinhy'>;
}
declare module 'proj4/lib/common/asinz.js' {
  declare module.exports: $Exports<'proj4/lib/common/asinz'>;
}
declare module 'proj4/lib/common/atanh.js' {
  declare module.exports: $Exports<'proj4/lib/common/atanh'>;
}
declare module 'proj4/lib/common/clens_cmplx.js' {
  declare module.exports: $Exports<'proj4/lib/common/clens_cmplx'>;
}
declare module 'proj4/lib/common/clens.js' {
  declare module.exports: $Exports<'proj4/lib/common/clens'>;
}
declare module 'proj4/lib/common/cosh.js' {
  declare module.exports: $Exports<'proj4/lib/common/cosh'>;
}
declare module 'proj4/lib/common/e0fn.js' {
  declare module.exports: $Exports<'proj4/lib/common/e0fn'>;
}
declare module 'proj4/lib/common/e1fn.js' {
  declare module.exports: $Exports<'proj4/lib/common/e1fn'>;
}
declare module 'proj4/lib/common/e2fn.js' {
  declare module.exports: $Exports<'proj4/lib/common/e2fn'>;
}
declare module 'proj4/lib/common/e3fn.js' {
  declare module.exports: $Exports<'proj4/lib/common/e3fn'>;
}
declare module 'proj4/lib/common/fL.js' {
  declare module.exports: $Exports<'proj4/lib/common/fL'>;
}
declare module 'proj4/lib/common/gatg.js' {
  declare module.exports: $Exports<'proj4/lib/common/gatg'>;
}
declare module 'proj4/lib/common/gN.js' {
  declare module.exports: $Exports<'proj4/lib/common/gN'>;
}
declare module 'proj4/lib/common/hypot.js' {
  declare module.exports: $Exports<'proj4/lib/common/hypot'>;
}
declare module 'proj4/lib/common/imlfn.js' {
  declare module.exports: $Exports<'proj4/lib/common/imlfn'>;
}
declare module 'proj4/lib/common/inverseNadCvt.js' {
  declare module.exports: $Exports<'proj4/lib/common/inverseNadCvt'>;
}
declare module 'proj4/lib/common/invlatiso.js' {
  declare module.exports: $Exports<'proj4/lib/common/invlatiso'>;
}
declare module 'proj4/lib/common/iqsfnz.js' {
  declare module.exports: $Exports<'proj4/lib/common/iqsfnz'>;
}
declare module 'proj4/lib/common/latiso.js' {
  declare module.exports: $Exports<'proj4/lib/common/latiso'>;
}
declare module 'proj4/lib/common/log1py.js' {
  declare module.exports: $Exports<'proj4/lib/common/log1py'>;
}
declare module 'proj4/lib/common/mlfn.js' {
  declare module.exports: $Exports<'proj4/lib/common/mlfn'>;
}
declare module 'proj4/lib/common/msfnz.js' {
  declare module.exports: $Exports<'proj4/lib/common/msfnz'>;
}
declare module 'proj4/lib/common/nad_cvt.js' {
  declare module.exports: $Exports<'proj4/lib/common/nad_cvt'>;
}
declare module 'proj4/lib/common/nad_intr.js' {
  declare module.exports: $Exports<'proj4/lib/common/nad_intr'>;
}
declare module 'proj4/lib/common/nadInterBreakout.js' {
  declare module.exports: $Exports<'proj4/lib/common/nadInterBreakout'>;
}
declare module 'proj4/lib/common/phi2z.js' {
  declare module.exports: $Exports<'proj4/lib/common/phi2z'>;
}
declare module 'proj4/lib/common/pj_enfn.js' {
  declare module.exports: $Exports<'proj4/lib/common/pj_enfn'>;
}
declare module 'proj4/lib/common/pj_inv_mlfn.js' {
  declare module.exports: $Exports<'proj4/lib/common/pj_inv_mlfn'>;
}
declare module 'proj4/lib/common/pj_mlfn.js' {
  declare module.exports: $Exports<'proj4/lib/common/pj_mlfn'>;
}
declare module 'proj4/lib/common/qsfnz.js' {
  declare module.exports: $Exports<'proj4/lib/common/qsfnz'>;
}
declare module 'proj4/lib/common/sign.js' {
  declare module.exports: $Exports<'proj4/lib/common/sign'>;
}
declare module 'proj4/lib/common/sinh.js' {
  declare module.exports: $Exports<'proj4/lib/common/sinh'>;
}
declare module 'proj4/lib/common/srat.js' {
  declare module.exports: $Exports<'proj4/lib/common/srat'>;
}
declare module 'proj4/lib/common/tanh.js' {
  declare module.exports: $Exports<'proj4/lib/common/tanh'>;
}
declare module 'proj4/lib/common/toPoint.js' {
  declare module.exports: $Exports<'proj4/lib/common/toPoint'>;
}
declare module 'proj4/lib/common/tsfnz.js' {
  declare module.exports: $Exports<'proj4/lib/common/tsfnz'>;
}
declare module 'proj4/lib/constants/Datum.js' {
  declare module.exports: $Exports<'proj4/lib/constants/Datum'>;
}
declare module 'proj4/lib/constants/Ellipsoid.js' {
  declare module.exports: $Exports<'proj4/lib/constants/Ellipsoid'>;
}
declare module 'proj4/lib/constants/PrimeMeridian.js' {
  declare module.exports: $Exports<'proj4/lib/constants/PrimeMeridian'>;
}
declare module 'proj4/lib/constants/units.js' {
  declare module.exports: $Exports<'proj4/lib/constants/units'>;
}
declare module 'proj4/lib/constants/values.js' {
  declare module.exports: $Exports<'proj4/lib/constants/values'>;
}
declare module 'proj4/lib/core.js' {
  declare module.exports: $Exports<'proj4/lib/core'>;
}
declare module 'proj4/lib/datum_transform.js' {
  declare module.exports: $Exports<'proj4/lib/datum_transform'>;
}
declare module 'proj4/lib/datum.js' {
  declare module.exports: $Exports<'proj4/lib/datum'>;
}
declare module 'proj4/lib/datumUtils.js' {
  declare module.exports: $Exports<'proj4/lib/datumUtils'>;
}
declare module 'proj4/lib/defs.js' {
  declare module.exports: $Exports<'proj4/lib/defs'>;
}
declare module 'proj4/lib/deriveConstants.js' {
  declare module.exports: $Exports<'proj4/lib/deriveConstants'>;
}
declare module 'proj4/lib/extend.js' {
  declare module.exports: $Exports<'proj4/lib/extend'>;
}
declare module 'proj4/lib/global.js' {
  declare module.exports: $Exports<'proj4/lib/global'>;
}
declare module 'proj4/lib/includedProjections.js' {
  declare module.exports: $Exports<'proj4/lib/includedProjections'>;
}
declare module 'proj4/lib/index.js' {
  declare module.exports: $Exports<'proj4/lib/index'>;
}
declare module 'proj4/lib/match.js' {
  declare module.exports: $Exports<'proj4/lib/match'>;
}
declare module 'proj4/lib/parseCode.js' {
  declare module.exports: $Exports<'proj4/lib/parseCode'>;
}
declare module 'proj4/lib/Point.js' {
  declare module.exports: $Exports<'proj4/lib/Point'>;
}
declare module 'proj4/lib/Proj.js' {
  declare module.exports: $Exports<'proj4/lib/Proj'>;
}
declare module 'proj4/lib/projections.js' {
  declare module.exports: $Exports<'proj4/lib/projections'>;
}
declare module 'proj4/lib/projections/aea.js' {
  declare module.exports: $Exports<'proj4/lib/projections/aea'>;
}
declare module 'proj4/lib/projections/aeqd.js' {
  declare module.exports: $Exports<'proj4/lib/projections/aeqd'>;
}
declare module 'proj4/lib/projections/cass.js' {
  declare module.exports: $Exports<'proj4/lib/projections/cass'>;
}
declare module 'proj4/lib/projections/cea.js' {
  declare module.exports: $Exports<'proj4/lib/projections/cea'>;
}
declare module 'proj4/lib/projections/eqc.js' {
  declare module.exports: $Exports<'proj4/lib/projections/eqc'>;
}
declare module 'proj4/lib/projections/eqdc.js' {
  declare module.exports: $Exports<'proj4/lib/projections/eqdc'>;
}
declare module 'proj4/lib/projections/equi.js' {
  declare module.exports: $Exports<'proj4/lib/projections/equi'>;
}
declare module 'proj4/lib/projections/etmerc.js' {
  declare module.exports: $Exports<'proj4/lib/projections/etmerc'>;
}
declare module 'proj4/lib/projections/gauss.js' {
  declare module.exports: $Exports<'proj4/lib/projections/gauss'>;
}
declare module 'proj4/lib/projections/gnom.js' {
  declare module.exports: $Exports<'proj4/lib/projections/gnom'>;
}
declare module 'proj4/lib/projections/gstmerc.js' {
  declare module.exports: $Exports<'proj4/lib/projections/gstmerc'>;
}
declare module 'proj4/lib/projections/krovak.js' {
  declare module.exports: $Exports<'proj4/lib/projections/krovak'>;
}
declare module 'proj4/lib/projections/laea.js' {
  declare module.exports: $Exports<'proj4/lib/projections/laea'>;
}
declare module 'proj4/lib/projections/lcc.js' {
  declare module.exports: $Exports<'proj4/lib/projections/lcc'>;
}
declare module 'proj4/lib/projections/longlat.js' {
  declare module.exports: $Exports<'proj4/lib/projections/longlat'>;
}
declare module 'proj4/lib/projections/merc.js' {
  declare module.exports: $Exports<'proj4/lib/projections/merc'>;
}
declare module 'proj4/lib/projections/mill.js' {
  declare module.exports: $Exports<'proj4/lib/projections/mill'>;
}
declare module 'proj4/lib/projections/moll.js' {
  declare module.exports: $Exports<'proj4/lib/projections/moll'>;
}
declare module 'proj4/lib/projections/nzmg.js' {
  declare module.exports: $Exports<'proj4/lib/projections/nzmg'>;
}
declare module 'proj4/lib/projections/omerc.js' {
  declare module.exports: $Exports<'proj4/lib/projections/omerc'>;
}
declare module 'proj4/lib/projections/ortho.js' {
  declare module.exports: $Exports<'proj4/lib/projections/ortho'>;
}
declare module 'proj4/lib/projections/poly.js' {
  declare module.exports: $Exports<'proj4/lib/projections/poly'>;
}
declare module 'proj4/lib/projections/sinu.js' {
  declare module.exports: $Exports<'proj4/lib/projections/sinu'>;
}
declare module 'proj4/lib/projections/somerc.js' {
  declare module.exports: $Exports<'proj4/lib/projections/somerc'>;
}
declare module 'proj4/lib/projections/stere.js' {
  declare module.exports: $Exports<'proj4/lib/projections/stere'>;
}
declare module 'proj4/lib/projections/sterea.js' {
  declare module.exports: $Exports<'proj4/lib/projections/sterea'>;
}
declare module 'proj4/lib/projections/tmerc.js' {
  declare module.exports: $Exports<'proj4/lib/projections/tmerc'>;
}
declare module 'proj4/lib/projections/utm.js' {
  declare module.exports: $Exports<'proj4/lib/projections/utm'>;
}
declare module 'proj4/lib/projections/vandg.js' {
  declare module.exports: $Exports<'proj4/lib/projections/vandg'>;
}
declare module 'proj4/lib/projString.js' {
  declare module.exports: $Exports<'proj4/lib/projString'>;
}
declare module 'proj4/lib/transform.js' {
  declare module.exports: $Exports<'proj4/lib/transform'>;
}
declare module 'proj4/lib/version.js' {
  declare module.exports: $Exports<'proj4/lib/version'>;
}
declare module 'proj4/projs.js' {
  declare module.exports: $Exports<'proj4/projs'>;
}
declare module 'proj4/test/package.json.js' {
  declare module.exports: $Exports<'proj4/test/package.json'>;
}
declare module 'proj4/test/test.js' {
  declare module.exports: $Exports<'proj4/test/test'>;
}
declare module 'proj4/test/testData.js' {
  declare module.exports: $Exports<'proj4/test/testData'>;
}
