// flow-typed signature: 87063f9fb6949e32f71adf90e1b2b2c4
// flow-typed version: <<STUB>>/react-router_v^1.0.0-rc3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/es6/AsyncUtils' {
  declare module.exports: any;
}

declare module 'react-router/es6/computeChangedRoutes' {
  declare module.exports: any;
}

declare module 'react-router/es6/getComponents' {
  declare module.exports: any;
}

declare module 'react-router/es6/getRouteParams' {
  declare module.exports: any;
}

declare module 'react-router/es6/History' {
  declare module.exports: any;
}

declare module 'react-router/es6/index' {
  declare module.exports: any;
}

declare module 'react-router/es6/IndexLink' {
  declare module.exports: any;
}

declare module 'react-router/es6/IndexRedirect' {
  declare module.exports: any;
}

declare module 'react-router/es6/IndexRoute' {
  declare module.exports: any;
}

declare module 'react-router/es6/isActive' {
  declare module.exports: any;
}

declare module 'react-router/es6/Lifecycle' {
  declare module.exports: any;
}

declare module 'react-router/es6/Link' {
  declare module.exports: any;
}

declare module 'react-router/es6/match' {
  declare module.exports: any;
}

declare module 'react-router/es6/matchRoutes' {
  declare module.exports: any;
}

declare module 'react-router/es6/PatternUtils' {
  declare module.exports: any;
}

declare module 'react-router/es6/PropTypes' {
  declare module.exports: any;
}

declare module 'react-router/es6/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/es6/Route' {
  declare module.exports: any;
}

declare module 'react-router/es6/RouteContext' {
  declare module.exports: any;
}

declare module 'react-router/es6/Router' {
  declare module.exports: any;
}

declare module 'react-router/es6/RouteUtils' {
  declare module.exports: any;
}

declare module 'react-router/es6/RoutingContext' {
  declare module.exports: any;
}

declare module 'react-router/es6/TransitionUtils' {
  declare module.exports: any;
}

declare module 'react-router/es6/useRoutes' {
  declare module.exports: any;
}

declare module 'react-router/lib/AsyncUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/computeChangedRoutes' {
  declare module.exports: any;
}

declare module 'react-router/lib/getComponents' {
  declare module.exports: any;
}

declare module 'react-router/lib/getRouteParams' {
  declare module.exports: any;
}

declare module 'react-router/lib/History' {
  declare module.exports: any;
}

declare module 'react-router/lib/index' {
  declare module.exports: any;
}

declare module 'react-router/lib/IndexLink' {
  declare module.exports: any;
}

declare module 'react-router/lib/IndexRedirect' {
  declare module.exports: any;
}

declare module 'react-router/lib/IndexRoute' {
  declare module.exports: any;
}

declare module 'react-router/lib/isActive' {
  declare module.exports: any;
}

declare module 'react-router/lib/Lifecycle' {
  declare module.exports: any;
}

declare module 'react-router/lib/Link' {
  declare module.exports: any;
}

declare module 'react-router/lib/match' {
  declare module.exports: any;
}

declare module 'react-router/lib/matchRoutes' {
  declare module.exports: any;
}

declare module 'react-router/lib/PatternUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/PropTypes' {
  declare module.exports: any;
}

declare module 'react-router/lib/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/lib/Route' {
  declare module.exports: any;
}

declare module 'react-router/lib/RouteContext' {
  declare module.exports: any;
}

declare module 'react-router/lib/Router' {
  declare module.exports: any;
}

declare module 'react-router/lib/RouteUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/RoutingContext' {
  declare module.exports: any;
}

declare module 'react-router/lib/TransitionUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/useRoutes' {
  declare module.exports: any;
}

declare module 'react-router/npm-scripts/postinstall' {
  declare module.exports: any;
}

declare module 'react-router/umd/ReactRouter' {
  declare module.exports: any;
}

declare module 'react-router/umd/ReactRouter.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/es6/AsyncUtils.js' {
  declare module.exports: $Exports<'react-router/es6/AsyncUtils'>;
}
declare module 'react-router/es6/computeChangedRoutes.js' {
  declare module.exports: $Exports<'react-router/es6/computeChangedRoutes'>;
}
declare module 'react-router/es6/getComponents.js' {
  declare module.exports: $Exports<'react-router/es6/getComponents'>;
}
declare module 'react-router/es6/getRouteParams.js' {
  declare module.exports: $Exports<'react-router/es6/getRouteParams'>;
}
declare module 'react-router/es6/History.js' {
  declare module.exports: $Exports<'react-router/es6/History'>;
}
declare module 'react-router/es6/index.js' {
  declare module.exports: $Exports<'react-router/es6/index'>;
}
declare module 'react-router/es6/IndexLink.js' {
  declare module.exports: $Exports<'react-router/es6/IndexLink'>;
}
declare module 'react-router/es6/IndexRedirect.js' {
  declare module.exports: $Exports<'react-router/es6/IndexRedirect'>;
}
declare module 'react-router/es6/IndexRoute.js' {
  declare module.exports: $Exports<'react-router/es6/IndexRoute'>;
}
declare module 'react-router/es6/isActive.js' {
  declare module.exports: $Exports<'react-router/es6/isActive'>;
}
declare module 'react-router/es6/Lifecycle.js' {
  declare module.exports: $Exports<'react-router/es6/Lifecycle'>;
}
declare module 'react-router/es6/Link.js' {
  declare module.exports: $Exports<'react-router/es6/Link'>;
}
declare module 'react-router/es6/match.js' {
  declare module.exports: $Exports<'react-router/es6/match'>;
}
declare module 'react-router/es6/matchRoutes.js' {
  declare module.exports: $Exports<'react-router/es6/matchRoutes'>;
}
declare module 'react-router/es6/PatternUtils.js' {
  declare module.exports: $Exports<'react-router/es6/PatternUtils'>;
}
declare module 'react-router/es6/PropTypes.js' {
  declare module.exports: $Exports<'react-router/es6/PropTypes'>;
}
declare module 'react-router/es6/Redirect.js' {
  declare module.exports: $Exports<'react-router/es6/Redirect'>;
}
declare module 'react-router/es6/Route.js' {
  declare module.exports: $Exports<'react-router/es6/Route'>;
}
declare module 'react-router/es6/RouteContext.js' {
  declare module.exports: $Exports<'react-router/es6/RouteContext'>;
}
declare module 'react-router/es6/Router.js' {
  declare module.exports: $Exports<'react-router/es6/Router'>;
}
declare module 'react-router/es6/RouteUtils.js' {
  declare module.exports: $Exports<'react-router/es6/RouteUtils'>;
}
declare module 'react-router/es6/RoutingContext.js' {
  declare module.exports: $Exports<'react-router/es6/RoutingContext'>;
}
declare module 'react-router/es6/TransitionUtils.js' {
  declare module.exports: $Exports<'react-router/es6/TransitionUtils'>;
}
declare module 'react-router/es6/useRoutes.js' {
  declare module.exports: $Exports<'react-router/es6/useRoutes'>;
}
declare module 'react-router/lib/AsyncUtils.js' {
  declare module.exports: $Exports<'react-router/lib/AsyncUtils'>;
}
declare module 'react-router/lib/computeChangedRoutes.js' {
  declare module.exports: $Exports<'react-router/lib/computeChangedRoutes'>;
}
declare module 'react-router/lib/getComponents.js' {
  declare module.exports: $Exports<'react-router/lib/getComponents'>;
}
declare module 'react-router/lib/getRouteParams.js' {
  declare module.exports: $Exports<'react-router/lib/getRouteParams'>;
}
declare module 'react-router/lib/History.js' {
  declare module.exports: $Exports<'react-router/lib/History'>;
}
declare module 'react-router/lib/index.js' {
  declare module.exports: $Exports<'react-router/lib/index'>;
}
declare module 'react-router/lib/IndexLink.js' {
  declare module.exports: $Exports<'react-router/lib/IndexLink'>;
}
declare module 'react-router/lib/IndexRedirect.js' {
  declare module.exports: $Exports<'react-router/lib/IndexRedirect'>;
}
declare module 'react-router/lib/IndexRoute.js' {
  declare module.exports: $Exports<'react-router/lib/IndexRoute'>;
}
declare module 'react-router/lib/isActive.js' {
  declare module.exports: $Exports<'react-router/lib/isActive'>;
}
declare module 'react-router/lib/Lifecycle.js' {
  declare module.exports: $Exports<'react-router/lib/Lifecycle'>;
}
declare module 'react-router/lib/Link.js' {
  declare module.exports: $Exports<'react-router/lib/Link'>;
}
declare module 'react-router/lib/match.js' {
  declare module.exports: $Exports<'react-router/lib/match'>;
}
declare module 'react-router/lib/matchRoutes.js' {
  declare module.exports: $Exports<'react-router/lib/matchRoutes'>;
}
declare module 'react-router/lib/PatternUtils.js' {
  declare module.exports: $Exports<'react-router/lib/PatternUtils'>;
}
declare module 'react-router/lib/PropTypes.js' {
  declare module.exports: $Exports<'react-router/lib/PropTypes'>;
}
declare module 'react-router/lib/Redirect.js' {
  declare module.exports: $Exports<'react-router/lib/Redirect'>;
}
declare module 'react-router/lib/Route.js' {
  declare module.exports: $Exports<'react-router/lib/Route'>;
}
declare module 'react-router/lib/RouteContext.js' {
  declare module.exports: $Exports<'react-router/lib/RouteContext'>;
}
declare module 'react-router/lib/Router.js' {
  declare module.exports: $Exports<'react-router/lib/Router'>;
}
declare module 'react-router/lib/RouteUtils.js' {
  declare module.exports: $Exports<'react-router/lib/RouteUtils'>;
}
declare module 'react-router/lib/RoutingContext.js' {
  declare module.exports: $Exports<'react-router/lib/RoutingContext'>;
}
declare module 'react-router/lib/TransitionUtils.js' {
  declare module.exports: $Exports<'react-router/lib/TransitionUtils'>;
}
declare module 'react-router/lib/useRoutes.js' {
  declare module.exports: $Exports<'react-router/lib/useRoutes'>;
}
declare module 'react-router/npm-scripts/postinstall.js' {
  declare module.exports: $Exports<'react-router/npm-scripts/postinstall'>;
}
declare module 'react-router/umd/ReactRouter.js' {
  declare module.exports: $Exports<'react-router/umd/ReactRouter'>;
}
declare module 'react-router/umd/ReactRouter.min.js' {
  declare module.exports: $Exports<'react-router/umd/ReactRouter.min'>;
}
