// flow-typed signature: 91b19b1bf92dd50d8f44fdf3e4d7ae9b
// flow-typed version: <<STUB>>/scrolltop_v0.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrolltop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scrolltop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'scrolltop/index' {
  declare module.exports: $Exports<'scrolltop'>;
}
declare module 'scrolltop/index.js' {
  declare module.exports: $Exports<'scrolltop'>;
}
