// flow-typed signature: f5f10f3e133da56577810541883e8136
// flow-typed version: <<STUB>>/updeep_v^0.16.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'updeep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'updeep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'updeep/dist/constant' {
  declare module.exports: any;
}

declare module 'updeep/dist/freeze' {
  declare module.exports: any;
}

declare module 'updeep/dist/if' {
  declare module.exports: any;
}

declare module 'updeep/dist/ifElse' {
  declare module.exports: any;
}

declare module 'updeep/dist/index' {
  declare module.exports: any;
}

declare module 'updeep/dist/is' {
  declare module.exports: any;
}

declare module 'updeep/dist/map' {
  declare module.exports: any;
}

declare module 'updeep/dist/omit' {
  declare module.exports: any;
}

declare module 'updeep/dist/omitBy' {
  declare module.exports: any;
}

declare module 'updeep/dist/reject' {
  declare module.exports: any;
}

declare module 'updeep/dist/umd/updeep-standalone' {
  declare module.exports: any;
}

declare module 'updeep/dist/umd/updeep-standalone.min' {
  declare module.exports: any;
}

declare module 'updeep/dist/update' {
  declare module.exports: any;
}

declare module 'updeep/dist/updateIn' {
  declare module.exports: any;
}

declare module 'updeep/dist/util/curry' {
  declare module.exports: any;
}

declare module 'updeep/dist/util/splitPath' {
  declare module.exports: any;
}

declare module 'updeep/dist/withDefault' {
  declare module.exports: any;
}

declare module 'updeep/dist/wrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'updeep/dist/constant.js' {
  declare module.exports: $Exports<'updeep/dist/constant'>;
}
declare module 'updeep/dist/freeze.js' {
  declare module.exports: $Exports<'updeep/dist/freeze'>;
}
declare module 'updeep/dist/if.js' {
  declare module.exports: $Exports<'updeep/dist/if'>;
}
declare module 'updeep/dist/ifElse.js' {
  declare module.exports: $Exports<'updeep/dist/ifElse'>;
}
declare module 'updeep/dist/index.js' {
  declare module.exports: $Exports<'updeep/dist/index'>;
}
declare module 'updeep/dist/is.js' {
  declare module.exports: $Exports<'updeep/dist/is'>;
}
declare module 'updeep/dist/map.js' {
  declare module.exports: $Exports<'updeep/dist/map'>;
}
declare module 'updeep/dist/omit.js' {
  declare module.exports: $Exports<'updeep/dist/omit'>;
}
declare module 'updeep/dist/omitBy.js' {
  declare module.exports: $Exports<'updeep/dist/omitBy'>;
}
declare module 'updeep/dist/reject.js' {
  declare module.exports: $Exports<'updeep/dist/reject'>;
}
declare module 'updeep/dist/umd/updeep-standalone.js' {
  declare module.exports: $Exports<'updeep/dist/umd/updeep-standalone'>;
}
declare module 'updeep/dist/umd/updeep-standalone.min.js' {
  declare module.exports: $Exports<'updeep/dist/umd/updeep-standalone.min'>;
}
declare module 'updeep/dist/update.js' {
  declare module.exports: $Exports<'updeep/dist/update'>;
}
declare module 'updeep/dist/updateIn.js' {
  declare module.exports: $Exports<'updeep/dist/updateIn'>;
}
declare module 'updeep/dist/util/curry.js' {
  declare module.exports: $Exports<'updeep/dist/util/curry'>;
}
declare module 'updeep/dist/util/splitPath.js' {
  declare module.exports: $Exports<'updeep/dist/util/splitPath'>;
}
declare module 'updeep/dist/withDefault.js' {
  declare module.exports: $Exports<'updeep/dist/withDefault'>;
}
declare module 'updeep/dist/wrap.js' {
  declare module.exports: $Exports<'updeep/dist/wrap'>;
}
