name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-pnpm-node.yml@feat/RATY-319-pnpm-node-workflow
    secrets: inherit
    with:
      node-version: 22.x
      extra-commands: pnpm update-runtime-env