name: kerrokantasi-ui-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
<<<<<<< HEAD
<<<<<<< HEAD
      - run: HUSKY=0 yarn install --network-concurrency 1
=======
      - run: yarn cache clean
      - run: HUSKY=0 yarn install --frozen-lockfile
>>>>>>> 4bfa4148 (chore: i had placed the env var to wrong spot in command)
=======
      - run: yarn install --frozen-lockfile
>>>>>>> a9bbbcac (chore: resetting back to og ci pipeline)
      - run: yarn lint
      - run: yarn build